#ifndef ESP8266_FAIRY_LIGHTS_CONFIGS_H
#define ESP8266_FAIRY_LIGHTS_CONFIGS_H

#define SERIAL_BAUDRATE 500000
#define LED_PIN LED_BUILTIN


#define CH1_PIN LED_BUILTIN
#define CH2_PIN LED_BUILTIN
#define CH3_PIN LED_BUILTIN
#define CH4_PIN LED_BUILTIN
#define CH5_PIN LED_BUILTIN

#endif //ESP8266_FAIRY_LIGHTS_CONFIGS_H
